# ----- GitHub build DEPRECATED! Use Drone build --------
name: Update Images

on:
  workflow_dispatch:

env:
  ENV_DOCKER_REPO_NAME: ghcr.io/kazanexpress/qa-docker

jobs:
  build-publish-docker-images:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: script
      run: |
        echo "Job started at $(date '+%d/%m/%Y %H:%M:%S')";
        sudo apt update
        sudo apt install -y curl jq gettext
        ENV_DOCKER_PUSH_EXIST=false
        for imageFolder in ./images/* ; 
          do
          if [ -d "$imageFolder" ]; then
            ENV_DOCKER_IMAGE_NAME=$(basename $imageFolder); 
            UPDATE_IMAGE=false;
            source $imageFolder/.versions;
            source $imageFolder/.check;
            source $imageFolder/.build;
          fi;
        done
        if [ "$ENV_DOCKER_PUSH_EXIST" = true ]; then 
          echo "Pushing changes to repository...";
          git config user.name 'Machine User';
          git config user.email 'ghmachine@kazanexpress.ru';
          git commit -m"Commit new .versions file [skip ci]";
          git push origin HEAD:master;
          echo "Done.";
        fi

        echo "Job finished at $(date '+%d/%m/%Y %H:%M:%S'). Bye...";
