FROM summerwind/actions-runner-dind:${LATEST_RUNNER_VERSION}

USER root

RUN curl -s https://repos.azul.com/azul-repo.key | gpg --dearmor -o /usr/share/keyrings/azul.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/azul.gpg] https://repos.azul.com/zulu/deb stable main" | tee /etc/apt/sources.list.d/zulu.list && \
    apt update && \
    apt install zulu11-jdk -y
    
RUN apt install wget -y

RUN wget -q https://github.com/qa-guru/allure-notifications/releases/download/4.3.0/allure-notifications-4.3.0.jar -O /home/runner/notifications.jar

USER runner

LABEL org.opencontainers.image.source https://github.com/kazanexpress/qa-docker