FROM golang:1.21-alpine AS build
RUN apk update \
    && apk add git \
    && git version

RUN git clone https://github.com/aerokube/selenoid.git \
    && cd selenoid \
    && git checkout tags/${LATEST_SELENOID_VERSION}

RUN mkdir -p /dist \
    && cd selenoid \
    && GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -tags s3 -o /dist/selenoid_linux_amd64

FROM alpine:3

RUN apk add -U ca-certificates tzdata mailcap && rm -Rf /var/cache/apk/*

COPY --from=build /dist/selenoid_linux_amd64 /usr/bin/selenoid

EXPOSE 4444

ENTRYPOINT ["/usr/bin/selenoid", "-listen", ":4444", "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video/"]
