FROM summerwind/actions-runner-dind:${LATEST_RUNNER_VERSION}

USER root

RUN curl -s https://repos.azul.com/azul-repo.key | gpg --dearmor -o /usr/share/keyrings/azul.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/azul.gpg] https://repos.azul.com/zulu/deb stable main" | tee /etc/apt/sources.list.d/zulu.list && \
    apt update && \
    apt install zulu17-jdk -y
    
RUN apt install wget -y

ENV GRADLE_HOME=/opt/gradle
ENV GRADLE_VERSION 8.2.1
RUN set -o errexit -o nounset \
    && echo "Downloading Gradle" \
    && wget --no-verbose --output-document=gradle.zip "https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip" \
    && echo "Installing Gradle" \
    && unzip gradle.zip \
    && rm gradle.zip \
    && mv "gradle-${GRADLE_VERSION}" "${GRADLE_HOME}/" \
    && ln --symbolic "${GRADLE_HOME}/bin/gradle" /usr/bin/gradle \
    && echo "Testing Gradle installation" \
    && gradle --version

RUN wget -q https://github.com/allure-framework/allurectl/releases/download/${LATEST_ALLURECTL_VERSION}/allurectl_linux_amd64 -O /home/runner/allurectl && \
    chmod +x /home/runner/allurectl && \ 
    chown runner:runner /home/runner/allurectl

RUN wget -q https://github.com/qa-guru/allure-notifications/releases/download/4.3.0/allure-notifications-4.3.0.jar -O /home/runner/notifications.jar

USER runner
