FROM summerwind/actions-runner-dind:${LATEST_RUNNER_VERSION}

USER root

RUN set -ex && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    wget \
    gnupg \
    libgconf-2-4 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libgdk-pixbuf2.0-0 \
    libgtk-3-0 \
    libgbm-dev \
    libnss3-dev \
    libxss-dev \
    fonts-liberation \
    libasound2 \
    libu2f-udev \
    libvulkan1 \
    xdg-utils && \
    rm -rf /var/lib/apt/lists/*

RUN curl -s https://repos.azul.com/azul-repo.key | gpg --dearmor -o /usr/share/keyrings/azul.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/azul.gpg] https://repos.azul.com/zulu/deb stable main" | tee /etc/apt/sources.list.d/zulu.list && \
    apt update && \
    apt install zulu11-jdk -y

RUN wget -q https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${LATEST_CHROME_VERSION}-1_amd64.deb && \
    apt-get install -y --no-install-recommends ./google-chrome-stable_${LATEST_CHROME_VERSION}-1_amd64.deb

RUN wget -q https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${LATEST_CHROME_VERSION}/linux64/chromedriver-linux64.zip
RUN unzip chromedriver-linux64.zip  
RUN mv chromedriver /usr/bin/chromedriver
RUN chown runner:runner /usr/bin/chromedriver
RUN chmod +x /usr/bin/chromedriver

RUN wget -q https://github.com/allure-framework/allurectl/releases/download/${LATEST_ALLURECTL_VERSION}/allurectl_linux_amd64 -O /home/runner/allurectl && \
    chmod +x /home/runner/allurectl && \ 
    chown runner:runner /home/runner/allurectl

RUN wget -q https://github.com/qa-guru/allure-notifications/releases/download/4.3.0/allure-notifications-4.3.0.jar -O /home/runner/notifications.jar

USER runner
